### ISSUE TITLE
500 Error when visiting dev server

### ISSUE THREAD

**Issue by jtdaugh** [harrystech/prelaunchr#70]
I followed the README and am getting the following error when visiting localhost:5000. I'm on MacOS Sierra FWIW

 foreman start -f Procfile.dev
15:17:17 web.1         | started with pid 10343
15:17:17 worker.1      | started with pid 10344
15:17:17 mailcatcher.1 | started with pid 10345
15:17:17 web.1         | I, [2018-05-03T15:17:17.595010 #10343]  INFO -- : Refreshing Gem list
15:17:17 mailcatcher.1 | Starting MailCatcher
15:17:17 mailcatcher.1 | ==> smtp://127.0.0.1:1025
15:17:17 mailcatcher.1 | /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated
15:17:17 mailcatcher.1 | ==> http://127.0.0.1:1080
15:17:19 web.1         | I, [2018-05-03T15:17:19.613301 #10343]  INFO -- : listening on addr=0.0.0.0:5000 fd=10
15:17:19 web.1         | I, [2018-05-03T15:17:19.717514 #10343]  INFO -- : master process ready
15:17:19 web.1         | I, [2018-05-03T15:17:19.719006 #10348]  INFO -- : worker=0 ready
15:17:19 web.1         | I, [2018-05-03T15:17:19.719538 #10349]  INFO -- : worker=1 ready
15:17:19 web.1         | I, [2018-05-03T15:17:19.720606 #10350]  INFO -- : worker=2 ready
15:17:27 web.1         | E, [2018-05-03T15:17:27.308713 #10348] ERROR -- : app error: wrong number of arguments (given 16384, expected 0..1) (ArgumentError)
15:17:27 web.1         | E, [2018-05-03T15:17:27.308713 #10350] ERROR -- : app error: wrong number of arguments (given 16384, expected 0..1) (ArgumentError)
15:17:27 web.1         | E, [2018-05-03T15:17:27.309015 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_request.rb:79:in `kgio_wait_readable'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309115 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_request.rb:79:in `kgio_read!'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309118 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_request.rb:79:in `kgio_wait_readable'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309203 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_request.rb:79:in `read'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309286 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_request.rb:79:in `kgio_read!'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309378 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_request.rb:79:in `read'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309350 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:562:in `process_client'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309476 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:562:in `process_client'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309543 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:658:in `worker_loop'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309575 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:658:in `worker_loop'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309641 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309634 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309706 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:132:in `start'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309756 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/bin/unicorn:126:in `<top (required)>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309734 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:132:in `start'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309814 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/bin/unicorn:23:in `load'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309866 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/bin/unicorn:23:in `<top (required)>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309833 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/bin/unicorn:126:in `<top (required)>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309917 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309964 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310013 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
15:17:27 web.1         | E, [2018-05-03T15:17:27.309950 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/bin/unicorn:23:in `load'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310100 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310162 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310112 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/bin/unicorn:23:in `<top (required)>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310221 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310269 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310262 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310324 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310395 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310398 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310454 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310503 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310566 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310627 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310492 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310679 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310728 #10350] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310700 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310816 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310932 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
15:17:27 web.1         | E, [2018-05-03T15:17:27.310995 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
15:17:27 web.1         | E, [2018-05-03T15:17:27.311053 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
15:17:27 web.1         | E, [2018-05-03T15:17:27.311105 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
15:17:27 web.1         | E, [2018-05-03T15:17:27.311156 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
15:17:27 web.1         | E, [2018-05-03T15:17:27.311204 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.311250 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
15:17:27 web.1         | E, [2018-05-03T15:17:27.311296 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.311342 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
15:17:27 web.1         | E, [2018-05-03T15:17:27.311387 #10348] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.465152 #10349] ERROR -- : app error: wrong number of arguments (given 16384, expected 0..1) (ArgumentError)
15:17:27 web.1         | E, [2018-05-03T15:17:27.465690 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_request.rb:79:in `kgio_wait_readable'
15:17:27 web.1         | E, [2018-05-03T15:17:27.465879 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_request.rb:79:in `kgio_read!'
15:17:27 web.1         | E, [2018-05-03T15:17:27.466010 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_request.rb:79:in `read'
15:17:27 web.1         | E, [2018-05-03T15:17:27.466110 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:562:in `process_client'
15:17:27 web.1         | E, [2018-05-03T15:17:27.466207 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:658:in `worker_loop'
15:17:27 web.1         | E, [2018-05-03T15:17:27.466391 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
15:17:27 web.1         | E, [2018-05-03T15:17:27.466506 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:132:in `start'
15:17:27 web.1         | E, [2018-05-03T15:17:27.466613 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicorn-5.0.1/bin/unicorn:126:in `<top (required)>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.466722 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/bin/unicorn:23:in `load'
15:17:27 web.1         | E, [2018-05-03T15:17:27.466824 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/bin/unicorn:23:in `<top (required)>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.466924 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
15:17:27 web.1         | E, [2018-05-03T15:17:27.467046 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
15:17:27 web.1         | E, [2018-05-03T15:17:27.467148 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
15:17:27 web.1         | E, [2018-05-03T15:17:27.467283 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
15:17:27 web.1         | E, [2018-05-03T15:17:27.467382 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
15:17:27 web.1         | E, [2018-05-03T15:17:27.467472 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
15:17:27 web.1         | E, [2018-05-03T15:17:27.467540 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
15:17:27 web.1         | E, [2018-05-03T15:17:27.467627 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
15:17:27 web.1         | E, [2018-05-03T15:17:27.467705 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
15:17:27 web.1         | E, [2018-05-03T15:17:27.467771 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
15:17:27 web.1         | E, [2018-05-03T15:17:27.467963 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.468155 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
15:17:27 web.1         | E, [2018-05-03T15:17:27.468339 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
15:17:27 web.1         | E, [2018-05-03T15:17:27.468524 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
15:17:27 web.1         | E, [2018-05-03T15:17:27.468691 #10349] ERROR -- : /Users/jesse/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'

**Comment by jtdaugh** [comment]
Resolved by reverting to this commit: 33d2b74

**Comment by galencorey** [comment]
I am also seeing this issue

**Comment by agchou** [comment]
I reverted the commit and still have the same issue... Anyone else have this as well?

**Comment by vimota** [comment]
Try checking out this branch, it fixed it for me: #73
